### ISSUE TITLE
MenuPopoever doesn't work in the virtualized Datagrid. 

### ISSUE THREAD

**Issue by MatthewThornton** [microsoft/fluentui-contrib#137]
Adding  a `<MenuPopver>` component in the virtualized Datagrid doesn't work. 

There is no menu. 
<img width="434" alt="image" src="https://github.com/microsoft/fluentui-contrib/assets/973184/030202e2-5fb6-4a24-b413-32395ae620bd">

Here is a reproduction. 
[Repo](https://codesandbox.io/p/sandbox/fluentui-v9-datagrid-virtualization-forked-4hqjpf?file=%2Fexample.tsx%3A126%2C6&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltonghcx00063b6hsactlyml%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltonghcx00023b6hjnfmajpm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltonghcx00033b6h6kc14ngl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltonghcx00053b6h0m47pnuh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltonghcx00023b6hjnfmajpm%2522%253A%257B%2522id%2522%253A%2522cltonghcx00023b6hjnfmajpm%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltonghcx00053b6h0m47pnuh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltonghcx00043b6h73w5ocf9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltonghcx00053b6h0m47pnuh%2522%252C%2522activeTabId%2522%253A%2522cltonghcx00043b6h73w5ocf9%2522%257D%252C%2522cltonghcx00033b6h6kc14ngl%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltonghcx00033b6h6kc14ngl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by ling1726** [comment]
This should be fixed in the latest version of @fluentui/react-components and @fluentui-contrib/react-data-grid-react-window. The original virtualized DataGrid shipped from @fluentui is no longer supported 

Example: https://codesandbox.io/p/sandbox/fluentui-v9-datagrid-virtualization-forked-hv4nnm?file=%2Fexample.tsx%3A8%2C9-8%2C55
