### ISSUE TITLE
[Feat] Virtualized DataGrid with autoFitColumns: false

### ISSUE THREAD

**Issue by rocketBANG** [microsoft/fluentui-contrib#176]
For the virtualized dataGrid (@fluentui-contrib/react-data-grid-react-window), the scrollbar is on the body

This is fine if the columns all fit without a horizontal overflow, however if there is some horizontal scrollbar there's no way to scroll both the body and the headers at the same time. So when `autoFitColumns` is set to false, this causes issues

`overflow-x: auto` can be applied to the parent container, but that means the vertical scrollbar won't be visible unless the user scrolls all the way to the right
![image](https://github.com/microsoft/fluentui-contrib/assets/2422566/4c3b4fdb-c070-4ab2-a349-796d800ff6f5)
https://codesandbox.io/p/sandbox/datagrid-body-overflow-forked-ygzvhs?workspaceId=2e8388ff-7617-4f14-8fb7-fe6621520941

`overflow-x: auto` can be applied to the `DataGridBody`, but that means the `DataGridHeader`s won't scroll with the body and the column data and headers will be misaligned
![image](https://github.com/microsoft/fluentui-contrib/assets/2422566/02d608f6-93b0-40ce-861e-634a95f534b4)
https://codesandbox.io/p/sandbox/datagrid-bodysize-bug-forked-6xqrry?file=%2Fsrc%2Fexample.tsx

(for the sandboxes, try resizing some columns to be larger and then observe the scrollbar positions/behaviours)

**Comment by it950** [comment]
I have the same issue: https://github.com/microsoft/fluentui/issues/32837
fluentui v9's progress was slow, and it still wasn't a complete replacement for fluentui v8

**Comment by nanivijay** [comment]
+100
We have the same requirements

**Comment by ling1726** [comment]
@rocketBANG  wondering if just having a wrapping overflow container wouldn't be an easier solution? https://codesandbox.io/p/sandbox/datagrid-bodysize-bug-forked-6xqrry

**Comment by rocketBANG** [comment]
@ling1726 The issue with that approach is there's no way to see the vertical scroll bar unless the user scrolls all the way to the edge of the page. So then that's a potential usability/accessibility issue
