### ISSUE TITLE
actions slot for ChatMessage?

### ISSUE THREAD

**Issue by joe-chiu** [microsoft/fluentui-contrib#57]
Any plan to add actions slot for ChatMessage? ChatMyMessage has actions slot but not ChatMessage.
Trying to figure out how to add Teams app style reaction hover menu.

<img width="253" alt="image" src="https://github.com/microsoft/fluentui-contrib/assets/14063642/beb30511-4390-4b17-98a8-ccc7d929c222">

**Comment by ling1726** [comment]
There is no plan to add a slot for this. The `ChatMessage` is actually a custom Popover trigger https://github.com/microsoft/fluentui-contrib/blob/73f3909177ececcd0a81bd366ba00006b5360873/packages/react-chat/src/components/ChatMessage/useChatMessage.ts#L104

When you wrap a popover around a chat message it will automatically be positioned relative to the bubble. Here's an example https://codesandbox.io/p/sandbox/adoring-saha-tfh6yw?file=%2Fsrc%2Fexample.tsx%3A42%2C17
